import React from 'react';

//MUI imports
import { Typography, Container } from '@material-ui/core';

export default function PrivacyPolicy() {
   return (
      <Container maxWidth="lg" style={{ marginBottom: 25 }}>
         <div className="margin-top-80">
            <Typography variant="h4" align="center">
               PRIVACY POLICY
            </Typography>
            <Typography variant="body1">Effective date: 2020-12-24</Typography>
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2">
                  Welcome to <b>BLOOMBOOK TECHNOLOGY PRIVATE LIMITED.</b>
               </Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">2. Definitions</Typography>
               <Typography variant="body2" align="justify">
                  SERVICE means the https://stylediscover.in/ website operated
                  by BLOOMBOOK TECHNOLOGY PRIVATE LIMITED.
                  <br />
                  <b>PERSONAL DATA</b> means data about a living individual who
                  can be identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                  <br />
                  <b>USAGE DATA</b> is data collected automatically either
                  generated by the use of Service or from Service infrastructure
                  itself (for example, the duration of a page visit).
                  <br />
                  <b>COOKIES</b> are small files stored on your device (computer
                  or mobile device).
                  <br />
                  <b>DATA CONTROLLER</b> means a natural or legal person who
                  (either alone or jointly or in common with other persons)
                  determines the purposes for which and the manner in which any
                  personal data are, or are to be, processed. For the purpose of
                  this Privacy Policy, we are a Data Controller of your data.
                  <br />
                  <b>DATA PROCESSORS</b> (OR SERVICE PROVIDERS) means any
                  natural or legal person who processes the data on behalf of
                  the Data Controller. We may use the services of various
                  Service Providers in order to process your data more
                  effectively.
                  <br />
                  <b>DATA SUBJECT</b> is any living individual who is the
                  subject of Personal Data.
                  <br />
                  <b>THE USER</b> is the individual using our Service. The User
                  corresponds to the Data Subject, who is the subject of
                  Personal Data.
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">
                  3. Information Collection and Use
               </Typography>
               <Typography variant="body2" align="justify">
                  We collect several different types of information for various
                  purposes to provide and improve our Service to you.
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">
                  4. Types of Data Collected
               </Typography>
               <Typography variant="body2" align="justify">
                  Personal Data
                  <br />
                  While using our Service, we may ask you to provide us with
                  certain personally identifiable information that can be used
                  to contact or identify you (“Personal Data”). Personally
                  identifiable information may include, but is not limited to:
                  <br />
                  0.1. Email address
                  <br />
                  0.2. First name and last name
                  <br />
                  0.3. Phone number
                  <br />
                  0.4. Address, Country, State, Province, ZIP/Postal code, City
                  <br />
                  0.5. Cookies and Usage Data
                  <br />
                  We may use your Personal Data to contact you with newsletters,
                  marketing or promotional materials and other information that
                  may be of interest to you. You may opt out of receiving any,
                  or all, of these communications from us by following the
                  unsubscribe link.
                  <br />
                  Usage Data
                  <br />
                  We may also collect information that your browser sends
                  whenever you visit our Service or when you access Service by
                  or through any device (“Usage Data”).
                  <br />
                  This Usage Data may include information such as your
                  computer’s Internet Protocol address (e.g. IP address),
                  browser type, browser version, the pages of our Service that
                  you visit, the time and date of your visit, the time spent on
                  those pages, unique device identifiers and other diagnostic
                  data.
                  <br />
                  When you access Service with a device, this Usage Data may
                  include information such as the type of device you use, your
                  device unique ID, the IP address of your device, your device
                  operating system, the type of Internet browser you use, unique
                  device identifiers and other diagnostic data.
                  <br />
                  Location Data
                  <br />
                  We may use and store information about your location if you
                  give us permission to do so (“Location Data”). We use this
                  data to provide features of our Service, to improve and
                  customize our Service.
                  <br />
                  You can enable or disable location services when you use our
                  Service at any time by way of your device settings.
                  <br />
                  Tracking Cookies Data
                  <br />
                  We use cookies and similar tracking technologies to track the
                  activity on our Service and we hold certain information.
                  <br />
                  Cookies are files with a small amount of data which may
                  include an anonymous unique identifier. Cookies are sent to
                  your browser from a website and stored on your device. Other
                  tracking technologies are also used such as beacons, tags and
                  scripts to collect and track information and to improve and
                  analyze our Service.
                  <br />
                  You can instruct your browser to refuse all cookies or to
                  indicate when a cookie is being sent. However, if you do not
                  accept cookies, you may not be able to use some portions of
                  our Service.
                  <br />
                  Examples of Cookies we use:
                  <br />
                  0.1. Session Cookies: We use Session Cookies to operate our
                  Service.
                  <br />
                  0.2. Preference Cookies: We use Preference Cookies to remember
                  your preferences and various settings.
                  <br />
                  0.3. Security Cookies: We use Security Cookies for security
                  purposes.
                  <br />
                  0.4. Advertising Cookies: Advertising Cookies are used to
                  serve you with advertisements that may be relevant to you and
                  your interests.
                  <br />
                  Other Data
                  <br />
                  While using our Service, we may also collect the following
                  information: sex, age, date of birth, place of birth, passport
                  details, citizenship, registration at place of residence and
                  actual address, telephone number (work, mobile), details of
                  documents on education, qualification, professional training,
                  employment agreements, NDA agreements, information on bonuses
                  and compensation, information on marital status, family
                  members, social security (or other taxpayer identification)
                  number, office location and other data.
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
            <br />
            <div>
               <Typography variant="subtitle2">1. Introduction</Typography>
               <Typography variant="body2" align="justify">
                  BLOOMBOOK TECHNOLOGY PRIVATE LIMITED (“us”, “we”, or “our”)
                  operates https://stylediscover.in/ (hereinafter referred to as
                  “Service”). Our Privacy Policy governs your visit to
                  https://stylediscover.in/, and explains how we collect,
                  safeguard and disclose information that results from your use
                  of our Service. We use your data to provide and improve
                  Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless
                  otherwise defined in this Privacy Policy, the terms used in
                  this Privacy Policy have the same meanings as in our Terms and
                  Conditions. Our Terms and Conditions (“Terms”) govern all use
                  of our Service and together with the Privacy Policy
                  constitutes your agreement with us (“agreement”).
               </Typography>
            </div>
            <br />
         </div>
      </Container>
   );
}
